version: '3.1'

services:
  frontend:
    image: hopper-front-end
    container_name: hopper-frontend
    build:
      context: ./front-end
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
  backend:
    image: hopper-back-end
    container_name: hopper-backend
    build:
      context: ./hopper
    restart: always
    tty: true
    depends_on:
      - db
    ports:
      - "8080:8000"
  db:
    image: postgres
    container_name: hopper-db
    restart: always
    environment:
      POSTGRES_DB: hopper-executor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: igumug16
      PGDATA: /Library/PostgreSQL/14/data
    ports:
      - "54321:5432"