# Generated by Django 4.0.4 on 2022-05-15 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 9, 34, 31, 991884)),
        ),
    ]
