# Generated by Django 4.0.4 on 2022-05-15 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0005_alter_session_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 10, 22, 54, 308132)),
        ),
    ]
